# 1. Importing the library

In [1]:
#Using numpy as np is just a choice to shorten the text length "numpy". One can use numpy as well.

import numpy as np


Quick tip: Use Alt+Enter to execute and insert next cell below.
               Control + Enter to execute current cell only.
               Esc and A to enter a cell above.
               Esc and B to enter a cell below.

In [2]:
#Let's first start by creating a list of list

lst=[[10,12,13],[23,43,5],[34,54,0]]
lst

[[10, 12, 13], [23, 43, 5], [34, 54, 0]]

In [3]:
#Now let's make a numpy array out of it

arr = np.array(lst)

In [4]:
#Now, let's perform some functions on it

print("Dimensions of the array are:",arr.shape)
print("Array's datatype is:",arr.dtype)

Dimensions of the array are: (3, 3)
Array's datatype is: int32


# 2. Fetching values

In [5]:
#Using index for whole row
arr[0]

array([10, 12, 13])

In [6]:
#Using index for specific values

arr[0,2] 

13

In [60]:
#To get values at columns

'''The semicolon ":" is for all the rows and 2 is for the column number starting from 0.
   It says bring me the 2nd column's values in all the rows.'''
arr[:,2]

array([13,  5,  0])

# 3. Updating and Creation of  arrays

In [8]:
#Updating values at columns

'It says change the values of '0th' column in all rows. Semicolon is for all rows.' 
arr[:,0]=[1,2,3]
arr

array([[ 1, 12, 13],
       [ 2, 43,  5],
       [ 3, 54,  0]])

In [9]:
#To create an array of all zeroes.

arr1=np.zeros(6)

print("Array:",arr1)
print("Array datatype:",arr1.dtype)


Array: [0. 0. 0. 0. 0. 0.]
Array datatype: float64


In [10]:
#To create an array of all zeroes as integer values.

arr2=np.zeros(3,dtype=np.int)
arr2

#See the output. You will not see a decimal with 0.

array([0, 0, 0])

In [11]:
#To create an array of all ones.

'Only arrays of 0's and 1's can be made like that.' 
arr3=np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [20]:
#Generating an array with range

arr4=np.arange(5)
print("Array with a range: \n",arr4)

#Second method of generating an array with range

'np.arange(start,stop,step) only the starting value will be included in the result. End value will not be included.'

arr6=np.arange(2,20,2)    #It will start from 2 and end at 20 taking a step of 2. 
print("Array with a range bwtween 2 and 20 following a step of 2:\n", arr6)               

#Generating an array with direct values

arr7=np.array([2,3,10,4,1])
print("Array with direct values:\n",arr7)


Array with a range: 
 [0 1 2 3 4]
Array with a range bwtween 2 and 20 following a step of 2:
 [ 2  4  6  8 10 12 14 16 18]
Array with direct values:
 [ 2  3 10  4  1]


# 4. Basic Functions on arrays

In [13]:
#Multiplication, division, addition, etc with a number can be performed on array like down below. 

print(arr4*3)        #Multiplication by a number
print(arr4/2)        #Division: To get quotient
print(arr7%2)        #Division: To get remainder
print(arr7+10)       #Addtion of a number to the array
print(arr7-8)        #Subtraction of a number
print(arr4**2)       #Raising the array to a power

[ 0  3  6  9 12]
[0.  0.5 1.  1.5 2. ]
[0 1 0 0 1]
[12 13 20 14 11]
[-6 -5  2 -4 -7]
[ 0  1  4  9 16]


In [15]:
#All the basic functions can be perfromed between arrays too. 

arr8 = np.array([5,10,15,20,25])
arr9 = np.array([2,4,6,8,10])

print(arr8*arr9)        #Multiplication between the arrays
print(arr8/arr9)        #Division to get quotients as values
print(arr8+arr9)        #Addition between two arrays
print(arr8%arr9)        #Division to get remainders as values
print(arr8**arr9)       #Raising an array to the power of the another array

[ 10  40  90 160 250]
[2.5 2.5 2.5 2.5 2.5]
[ 7 14 21 28 35]
[1 2 3 4 5]
[        25      10000   11390625 -169803776 1977800241]


# 5. Copying in Numpy

In [57]:
#A direct approach to copy

arrA=np.array([10,20,30,40])
arrB=arrA            #A new array arrB is just a view to the same location where values of array arrA.
print("arrB:          ",arrB)
print("Is arrB arrA:  ", arrA is arrB)

arrA = arrA+100
print("\nNew Array arrA:", arrA)
print("Array arrB:    ", arrB)

'''Changes made in arrA will not reflect in arrB and vice versa.''' 

arrB = arrB+20
print("\nArray arrA:    ", arrA)
print("New Array arrB:", arrB)
#So now the same location has two views.

arrB:           [10 20 30 40]
Is arrB arrA:   True

New Array arrA: [110 120 130 140]
Array arrB:     [10 20 30 40]

Array arrA:     [110 120 130 140]
New Array arrB: [30 40 50 60]


In [69]:
#Will create an actual copy stored at another location. 

arrA=np.array([1,5,7,9])
arrD=arrA.copy()
print("arrD:         ",arrD)
print("Is arrD aarD: ", arrD is arrA)

'arrD and arrA are different. Any changes made to arrA will not reflect in arrD and vice versa. '
arrA= arrA+10
print("\nNew arrA is: ", arrA)
print("arrD is:     ", arrD)

arrD = arrD+100
print("\narrA is:     ", arrA)
print("New arrD is: ", arrD)

arrD:          [1 5 7 9]
Is arrD aarD:  False

New arrA is:  [11 15 17 19]
arrD is:      [1 5 7 9]

arrA is:      [11 15 17 19]
New arrD is:  [101 105 107 109]


A View is a window to the same memory location. There can be many views to a single location. 
That means whatever changes are done in view window will affect the original memory. 

In [70]:
#NumPy View

arrA=np.array([0,2,4,8])

arrE=arrA.view()
print("arrE:        ",arrE)
print("Is arrE arrC:", arrE is arrA)
 
'Changes made to arrA will not change arrE'   
arrA = arrA**3
print("\nNew arrA is: ", arrA)
print("arrE is:     ", arrE)

'Changes made to arrE will change arrA'
arrE= arrE+50
print("\nNew arrE is: ", arrE)
print("arrA is:     ", arrA)

arrE:         [0 2 4 8]
Is arrE arrC: False

New arrA is:  [  0   8  64 512]
arrE is:      [0 2 4 8]

New arrE is:  [50 52 54 58]
arrA is:      [  0   8  64 512]


# 6. Basic Array Methods 

In [106]:

#Creating an array with random values
arrR=np.random.randint(5,15,5)
print("Random values of array:",arrR)

#Comparing values of array
div=arrR%2==0
print("True for the above condition or not:",div)

Random values of array: [ 6 12  9 11  5]
True for the above condition or not: [ True  True False False False]


In [154]:
#Basic array methods
print("Minimum value in arrR:",arrR.min())
print("Minimum value's position:",arrR.argmin())

print("\nMaximum value in arrR:",arrR.max())
print("Maximum value's position:",arrR.argmax())

print("\nIf all the items are true return true:",div.all())
print("If any item is true return true:",div.any())

print("\nSum of values in arrR:",arrR.sum())
print("\nSquare root of values in arrR:",np.sqrt(arrR))


Minimum value in arrR: 5
Minimum value's position: 0

Maximum value in arrR: 12
Maximum value's position: 4

If all the items are true return true: False
If any item is true return true: True

Sum of values in arrR: 43

Square root of values in arrR: [2.23606798 2.44948974 3.         3.31662479 3.46410162]


In [54]:
arrH=np.random.randint(5,15,5)                             #(Start,Stop,Number) Where number is the number of values this time

print("Originally the arrH looks like:\n",arrH)
print("After Sorting:\n",np.sort(arrH))
print("The index of the sorted elements in the original arrH were:\n",np.argsort(arrH))     #arg brings the index of the values
arrH.sort()
print("Just another way to sort:\n",arrH)

Originally the arrH looks like:
 [ 8  7 10 10 14]
After Sorting:
 [ 7  8 10 10 14]
The index of the sorted elements in the original arrH were:
 [1 0 2 3 4]
Just another way to sort:
 [ 7  8 10 10 14]


In [55]:
#Will bring the values of arrH that are sorted by argsort
arrH[arrH.argsort()]

array([ 7,  8, 10, 10, 14])

In [56]:
#Finding the transpose of an array(matrice)

arrI=[[2,3,4],[10,20,30]]
arr.transpose()

array([[ 1,  2,  3],
       [12, 43, 54],
       [13,  5,  0]])

One should always experiment with whatsoever is given. That's how leanring is done.
There can be methods or things not shown here but that should not stop you from learning more. 